### ISSUE TITLE
Summary of Failures systemd building

### ISSUE THREAD

**Issue by unforgivablesin** [systemd/particleos#16]
When I run the following command to build systemd I am met with these failures. Any ideas?

```bash
mkosi -t none
```

```
Summary of Failures:

1002/1715 systemd:test / test-loopback                                      FAIL              0.01s   exit status 1
1047/1715 systemd:resolve / test-resolved-stream                            FAIL              5.02s   killed by signal 6 SIGABRT

Ok:                 1678
Expected Fail:      0   
Fail:               2   
Unexpected Pass:    0   
Skipped:            35  
Timeout:            0   

Full log written to /work/build/meson-logs/testlog.txt
error: Bad exit status from /var/tmp/rpm-tmp.tZ5Wd0 (%check)
```

**Comment by unforgivablesin** [comment]
Apologies. Distro, Fedora 41 Silverblue. Kernel `6.11.5-300.fc41.x86_64`. Mkosi `mkosi 25~devel`.

When I try to cat the logs it says they dont exist.

**Comment by DaanDeMeyer** [comment]
Please just scroll up a little and the failed test output will be there in plain sight.

**Comment by unforgivablesin** [comment]
Im not sure if this is user error or not. I followed the instructions.

**Comment by DaanDeMeyer** [comment]
I pushed a commit to mkosi that will result in a clearer error

**Comment by unforgivablesin** [comment]
Thank you. I will test it shortly when I'm back home

**Comment by unforgivablesin** [comment]
Hello. I reinstalled and it still doesnt work, this is the output I have gotten.

```bash
user@localhost-live:~/Desktop/particleos$ sudo mkosi -d fedora -f
\u2023 /home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64.cache does not exist, not reusing cached images
\u2023 Running clean script /home/user/Desktop/particleos/mkosi.clean\u2026
\u2023 /home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64~default-initrd.cache does not exist, not reusing cached images
\u2023 Validating certificates and keys
No certificate specified, use --certificate=
\u2023 "'/home/user/Desktop/particleos/systemd/build/mkosi.builddir/fedora~rawhide~x86-64/systemd-keyutil' validate" returned non-zero exit code 1.
user@localhost-live:~/Desktop/particleos$ mkosi --version
mkosi 25~devel
user@localhost-live:~/Desktop/particleos$ 
```

Latest commit is:

```
commit 7abaed33bd4ccad27d2e7b47ca16884cde85c6c8 (HEAD -> main, origin/main, origin/HEAD)
Author: Daan De Meyer <daan.j.demeyer@gmail.com>
Date:   Sun Dec 1 12:00:10 2024 +0100

    Only run systemd-keyutil if secure boot key and cert exist
```

**Comment by unforgivablesin** [comment]
Any ideas?

**Comment by DaanDeMeyer** [comment]
Added another commit to mkosi, please pull and try again

**Comment by unforgivablesin** [comment]
Hello, thank you. This is my output now.

```bash
user@fedora:~/Desktop/particleos$ sudo mkosi -t disk -d fedora -f
\u2023 /home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64.cache does not exist, not reusing cached images
\u2023 Running clean script /home/user/Desktop/particleos/mkosi.clean\u2026
\u2023 Removing cache entries of ParticleOS image\u2026
\u2023 /home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64~default-initrd.cache does not exist, not reusing cached images
\u2023 Validating certificates and keys
\u2023 Syncing package manager metadata
No matches were found for the following plugin name patterns while enabling libdnf plugins: builddep, versionlock
No matches were found for the following plugin name patterns while disabling libdnf plugins: *
Updating and loading repositories:
Repositories loaded.
Metadata cache created.
Create subvolume '/work/home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64.metadata.cache'
\u2023 Copying repository metadata
Create snapshot of '/work/home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64.metadata.cache' in '/work/var/tmp/mkosi-metadata-p8glkujk'
\u2023 Building ParticleOS image
\u2023 /home/user/Desktop/particleos/mkosi.cache/fedora~rawhide~x86-64.cache does not exist, not reusing cached images
Create subvolume '/work/var/tmp/mkosi-workspace-9kebxhc6/root'
\u2023  Copying in extra packages\u2026
\u2023  Rebuilding local package repository
\u2023 createrepo_c not found.
```

**Comment by DaanDeMeyer** [comment]
Seems pretty self explanatory no?

**Comment by unforgivablesin** [comment]
Apologies. I had no idea createrepo_c was a package. That wasn't very obvious to me actually.

**Comment by unforgivablesin** [comment]
The issue is resolved. Thank you.
